fix(ci): fix permision issure for ecr login

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,28 @@
 stages:
+  - login
   - build
+
+aws-login:
+  stage: login
+  image:
+    name: amazon/aws-cli:latest
+    entrypoint: [""]
+  script:
+    - mkdir -p .docker
+    - |
+      if [ -z "$AWS_DEFAULT_REGION" ] || [ -z "$ECR_REGISTRY" ]; then
+        echo "Error: AWS_DEFAULT_REGION or ECR_REGISTRY is not set."
+        exit 1
+      fi
+    - PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
+    - AUTH=$(echo -n "AWS:$PASSWORD" | base64 | tr -d '\n')
+    - echo "{\"auths\":{\"$ECR_REGISTRY\":{\"auth\":\"$AUTH\"}}}" > .docker/config.json
+  artifacts:
+    paths:
+      - .docker/config.json
+    expire_in: 1 hour
+  tags:
+    - ec2-runner
 
 .template-build:
   stage: build
@@ -12,9 +35,8 @@ stages:
     TARGET_DOCKER_FILE: Dockerfile
     SSL_CERT_DIR: /etc/ssl/certs
   before_script:
-    - apk add --no-cache aws-cli
-    - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
-      docker login --username AWS --password-stdin $ECR_REGISTRY
+    - mkdir -p ~/.docker
+    - cp .docker/config.json ~/.docker/config.json
   script:
     - test -n "${BUILD_CONTEXT_DIR}" || (echo "BUILD_CONTEXT_DIR is not set" && exit 1)
     - test -n "${TARGET_DOCKER_FILE}" || (echo "TARGET_DOCKER_FILE is not set" && exit 1)
